### ISSUE TITLE
support Gmail/Outlook application password ?

### ISSUE THREAD

**Issue by spysir** [cyrinux/imap2gotify#203]
support Gmail/Outlook application password ?

**Comment by cyrinux** [comment]
Hi,
Thanks for the suggestion, but feel free the open a pull request if you can. 
I don't plan to add this feature myself as I use this software less and don't have this need. 
It was aim to support as the name say imap protocol only.
I suppose it easy to add with the good library.

**Comment by spysir** [comment]
> Hi, Thanks for the suggestion, but feel free the open a pull request if you can. I don't plan to add this feature myself as I use this software less and don't have this need. It was aim to support as the name say imap protocol only. I suppose it easy to add with the good library.你好 感谢您的建议，但如果可以的话，请随时打开拉取请求。 我不打算自己添加此功能，因为我较少使用此软件并且没有此需求。 顾名思义，它旨在支持imap协议。 我想很容易用好的库添加。

After testing, Outlook app passwords are now supported
